# Generated by Django 4.0.3 on 2022-03-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_business_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('product_url', models.URLField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('product_rating', models.FloatField(blank=True, null=True)),
                ('nb_reviewers', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('keyword', models.TextField()),
                ('topic_perc_contrib', models.FloatField()),
                ('dominant_topic', models.IntegerField(blank=True, null=True)),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lefouineur.product')),
            ],
        ),
    ]
